extends Node

const CARDS = [
	{
		"id": 1,
		"name": "Avanço",
		"type": "linear",
		"x": 8.0,
		"y": 0.0,
		"energy_cost": 1,
		"draw_chance": 70,
	},
	{
		"id": 2,
		"name": "Elevar",
		"type": "diagonal",
		"x": 5.0,
		"y": 2.0,
		"energy_cost": 1,
		"draw_chance": 15,
	},
	{
		"id": 3,
		"name": "Arco",
		"type": "quadratic",
		"coefficient": "a",
		"value": 0.35,
		"energy_cost": 1,
		"draw_chance": 5,
	},
	{
		"id": 4,
		"name": "Queda",
		"type": "quadratic",
		"coefficient": "a",
		"value": -0.35,
		"energy_cost": 1,
		"draw_chance": 5,
	},
	{
		"id": 5,
		"name": "Onda",
		"type": "special",
		"special_type": "wave",
		"amplitude": 3.0,
		"frequency": 4.0,
		"length": 12.0,
		"energy_cost": 2,
		"draw_chance": 10,
	},
	{
		"id": 6,
		"name": "Salto",
		"type": "linear",
		"x": 0.0,
		"y": 2.0,
		"energy_cost": 1,
		"draw_chance": 20,
	},
	{
		"id": 7,
		"name": "Degrau",
		"type": "linear",
		"x": 3.0,
		"y": 0.0,
		"energy_cost": 1,
		"draw_chance": 20,
	},
	{
		"id": 8,
		"name": "Impulso",
		"type": "diagonal",
		"x": 4.0,
		"y": 2.0,
		"energy_cost": 1,
		"draw_chance": 12,
	},
	{
		"id": 9,
		"name": "Colina",
		"type": "quadratic",
		"coefficient": "a",
		"value": 0.35,
		"energy_cost": 1,
		"draw_chance": 8,
	},
	{
		"id": 10,
		"name": "Mergulho",
		"type": "quadratic",
		"coefficient": "a",
		"value": -0.35,
		"energy_cost": 1,
		"draw_chance": 8,
	},
	{
		"id": 11,
		"name": "Oscilar",
		"type": "special",
		"special_type": "wave",
		"amplitude": 1.5,
		"frequency": 2.0,
		"length": 4.0,
		"energy_cost": 1,
		"draw_chance": 8,
	},
	{
		"id": 12,
		"name": "Maré",
		"type": "special",
		"special_type": "wave",
		"amplitude": 1.5,
		"frequency": 2.0,
		"length": 8.0,
		"energy_cost": 1,
		"draw_chance": 6,
	},
	{
		"id": 13,
		"name": "Ascensão",
		"type": "diagonal",
		"x": 3.0,
		"y": 2.0,
		"energy_cost": 1,
		"draw_chance": 10,
	},
	{
		"id": 14,
		"name": "Travessia",
		"type": "linear",
		"x": 4.0,
		"y": 0.0,
		"energy_cost": 1,
		"draw_chance": 25,
	},
	{
		"id": 15,
		"name": "Vale",
		"type": "quadratic",
		"coefficient": "a",
		"value": -0.35,
		"energy_cost": 1,
		"draw_chance": 10,
	}
]
